import os

from dotenv import load_dotenv


load_dotenv()


def env_int(name, default):
    return int(os.getenv(name, default))


TAGS = [
    "F_1 GIRIS BIYET NO",
    "F_1 CIKIS BIYET NO",
    "F_1 BIYET HAM ISI",
    "F_1 BIYET PIK ISI",
    "F_1 BIYET ISINMA SURESI_DK",
    "F_1 BIYET ISINMA SURESI_SN",
    "F_1 V_YATAK GIRIS ISI",
    "F_1 V_YATAK CIKIS ISI",
    "F_1 V_YATAKDA BEKLEME SURESI_DK",
    "F_1 V_YATAKDA BEKLEME SURESI_SN",
    "F_2 GIRIS BIYET NO",
    "F_2 CIKIS BIYET NO",
    "F_2 BIYET HAM ISI",
    "F_2 BIYET PIK ISI",
    "F_2 BIYET ISINMA SURESI_DK",
    "F_2 BIYET ISINMA SURESI_SN",
    "F_2 V_YATAK GIRIS ISI",
    "F_2 V_YATAK CIKIS ISI",
    "F_2 V_YATAKDA BEKLEME SURESI_DK",
    "F_2 V_YATAKDA BEKLEME SURESI_SN",
    "FIRIN_1 ORTAM ISI",
    "FIRIN_2 ORTAM ISI",
    "FIRIN_1 ORTAM ISI TREND",
    "FIRIN_2 ORTAM ISI TREND",
]

MODBUS_HOST = os.getenv("MODBUS_HOST", "172.16.48.185")
MODBUS_PORT = env_int("MODBUS_PORT", 502)
MODBUS_DEVICE_ID = env_int("MODBUS_DEVICE_ID", 1)
START_ADDRESS = env_int("START_ADDRESS", 4506)
START_MODBUS_ADDRESS = env_int("START_MODBUS_ADDRESS", 44507)
REGISTER_COUNT = env_int("REGISTER_COUNT", 24)
POLL_INTERVAL_SECONDS = env_int("POLL_INTERVAL_SECONDS", 1)

DB_HOST = os.getenv("DB_HOST")
DB_PORT = env_int("DB_PORT", 5432)
DB_NAME = os.getenv("DB_NAME")
DB_USER = os.getenv("DB_USER")
DB_PASS = os.getenv("DB_PASS")

DASHBOARD_HOST = os.getenv("DASHBOARD_HOST", "127.0.0.1")
DASHBOARD_PORT = env_int("DASHBOARD_PORT", 5059)
DASHBOARD_STALE_MINUTES = env_int("DASHBOARD_STALE_MINUTES", 5)
WARN_VALUE_THRESHOLD = env_int("WARN_VALUE_THRESHOLD", 500)
CRITICAL_VALUE_THRESHOLD = env_int("CRITICAL_VALUE_THRESHOLD", 1000)
