name: plcmodbuscollector

services:
  plcmodbuscollector:
    build:
      context: .
      dockerfile: Dockerfile
    image: plcmodbuscollector
    container_name: plcmodbuscollector
    environment:
      DB_HOST: ${DB_HOST:-172.16.49.2}
      DB_PORT: ${DB_PORT:-5432}
      DB_NAME: ${DB_NAME:-modbus}
      DB_USER: ${DB_USER:-modbus_user}
      DB_PASS: ${DB_PASS:-0D6XdbKh7oH5p9T7}
      MODBUS_HOST: ${MODBUS_HOST:-172.16.48.185}
      MODBUS_PORT: ${MODBUS_PORT:-502}
      MODBUS_DEVICE_ID: ${MODBUS_DEVICE_ID:-1}
      START_ADDRESS: ${START_ADDRESS:-4506}
      START_MODBUS_ADDRESS: ${START_MODBUS_ADDRESS:-44507}
      REGISTER_COUNT: ${REGISTER_COUNT:-24}
      POLL_INTERVAL_SECONDS: ${POLL_INTERVAL_SECONDS:-1}
      DASHBOARD_HOST: ${DASHBOARD_HOST:-0.0.0.0}
      DASHBOARD_PORT: ${DASHBOARD_PORT:-5059}
      DASHBOARD_STALE_MINUTES: ${DASHBOARD_STALE_MINUTES:-5}
      WARN_VALUE_THRESHOLD: ${WARN_VALUE_THRESHOLD:-500}
      CRITICAL_VALUE_THRESHOLD: ${CRITICAL_VALUE_THRESHOLD:-1000}
    ports:
      - "5959:5059"
    restart: always
